
SET SQL DIALECT 3; 

/* CREATE DATABASE 'localhost:<CAMINHO>\POSTO.fdb' PAGE_SIZE 8192 DEFAULT CHARACTER SET UTF8; */

/*  Generators or sequences */
CREATE GENERATOR GEN_ABASTECIMENTO_ID START WITH 1;
CREATE GENERATOR GEN_BOMBA_ID START WITH 1;
CREATE GENERATOR GEN_TANQUE_ID START WITH 1;
CREATE GENERATOR GEN_TIPOCOMBUSTIVEL_ID START WITH 1;

COMMIT WORK;

/* Table: ABASTECIMENTO, Owner: SYSDBA */
CREATE TABLE ABASTECIMENTO (ID_ABASTECIMENTO INTEGER NOT NULL,
        ID_BOMBA INTEGER NOT NULL,
        DATA_HORA TIMESTAMP,
        QUANTIDADE DECIMAL(15, 3),
        VALOR DECIMAL(15, 2),
        PERCENTUAL_IMPOSTO DECIMAL(8, 2),
        VALOR_IMPOSTO DECIMAL(15, 2),
CONSTRAINT PK_ABASTECIMENTO PRIMARY KEY (ID_ABASTECIMENTO));

/* Table: BOMBA, Owner: SYSDBA */
CREATE TABLE BOMBA (ID_BOMBA INTEGER NOT NULL,
        NUMERO SMALLINT,
        ID_TANQUE INTEGER,
CONSTRAINT PK_BOMBA PRIMARY KEY (ID_BOMBA));

/* Table: TANQUE, Owner: SYSDBA */
CREATE TABLE TANQUE (ID_TANQUE INTEGER NOT NULL,
        NUMERO SMALLINT,
        ID_TIPO_COMBUSTIVEL INTEGER,
CONSTRAINT PK_TANQUE PRIMARY KEY (ID_TANQUE));

/* Table: TIPOCOMBUSTIVEL, Owner: SYSDBA */
CREATE TABLE TIPOCOMBUSTIVEL (ID_TIPO_COMBUSTIVEL INTEGER NOT NULL,
        DESCRICAO VARCHAR(30),
CONSTRAINT PK_TIPOCOMBUSTIVEL PRIMARY KEY (ID_TIPO_COMBUSTIVEL));

ALTER TABLE ABASTECIMENTO ADD CONSTRAINT FK_ABASTECIMENTO_BOMBA FOREIGN KEY (ID_BOMBA) REFERENCES BOMBA (ID_BOMBA);

ALTER TABLE BOMBA ADD CONSTRAINT FK_BOMBA_TANQUE FOREIGN KEY (ID_TANQUE) REFERENCES TANQUE (ID_TANQUE);

ALTER TABLE TANQUE ADD CONSTRAINT FK_TANQUE_TIPO_COMBUSTIVEL FOREIGN KEY (ID_TIPO_COMBUSTIVEL) REFERENCES TIPOCOMBUSTIVEL (ID_TIPO_COMBUSTIVEL);
SET TERM ^ ;

/* Triggers only will work for SQL triggers */
CREATE TRIGGER ABASTECIMENTO_BI FOR ABASTECIMENTO 
ACTIVE BEFORE INSERT POSITION 0 
as
begin
  if (new.id_abastecimento is null) then
    new.id_abastecimento = gen_id(gen_abastecimento_id,1);
end ^

CREATE TRIGGER BOMBA_BI FOR BOMBA 
ACTIVE BEFORE INSERT POSITION 0 
as
begin
  if (new.id_bomba is null) then
    new.id_bomba = gen_id(gen_bomba_id,1);
end ^

CREATE TRIGGER TANQUE_BI FOR TANQUE 
ACTIVE BEFORE INSERT POSITION 0 
as
begin
  if (new.id_tanque is null) then
    new.id_tanque = gen_id(gen_tanque_id,1);
end ^

CREATE TRIGGER TIPOCOMBUSTIVEL_BI FOR TIPOCOMBUSTIVEL 
ACTIVE BEFORE INSERT POSITION 0 
as
begin
  if (new.id_tipo_combustivel is null) then
    new.id_tipo_combustivel = gen_id(gen_tipocombustivel_id,1);
end ^


SET TERM ; ^
COMMIT WORK;

/* Carga Inicial */
INSERT INTO TIPOCOMBUSTIVEL (ID_TIPO_COMBUSTIVEL, DESCRICAO) VALUES (1, 'Gasolina');
INSERT INTO TIPOCOMBUSTIVEL (ID_TIPO_COMBUSTIVEL, DESCRICAO) VALUES (2, 'Óleo Diesel');


COMMIT WORK;

INSERT INTO TANQUE (ID_TANQUE, NUMERO, ID_TIPO_COMBUSTIVEL) VALUES (1, 1, 1);
INSERT INTO TANQUE (ID_TANQUE, NUMERO, ID_TIPO_COMBUSTIVEL) VALUES (2, 2, 2);


COMMIT WORK;

INSERT INTO BOMBA (ID_BOMBA, NUMERO, ID_TANQUE) VALUES (1, 1, 1);
INSERT INTO BOMBA (ID_BOMBA, NUMERO, ID_TANQUE) VALUES (2, 2, 1);
INSERT INTO BOMBA (ID_BOMBA, NUMERO, ID_TANQUE) VALUES (3, 3, 2);
INSERT INTO BOMBA (ID_BOMBA, NUMERO, ID_TANQUE) VALUES (4, 4, 2);


COMMIT WORK;
